[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@9.0.0 --force", "export PATH=$PATH:/root/.local/share/pnpm:/usr/local/lib/node_modules/.bin && pnpm install --filter api --frozen-lockfile=false"]

[phases.build]
cmds = ["export PATH=$PATH:/root/.local/share/pnpm:/usr/local/lib/node_modules/.bin && pnpm --filter api run build"]

[start]
cmd = "cd apps/api && node dist/index.js"