packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - msgpackr-extract

dangerouslyAllowAllBuilds: true
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
